### ISSUE TITLE
Criar wrap para regras de divisão na zoop (split)

### ISSUE THREAD

**Issue by guerra** [byebnk/zoop_ruby#4]
https://zoop.readme.io/v1/reference#regra-de-divis%C3%A3o

- [x] Recuperar detalhes de regra de divisão por transação
- [x] Criar regra de divisão por transação
- [x] Recupera detalhes de regra de divisão por transação
- [x] Alterar regra de divisão por transação
- [x] Remover regra de divisão por transação

**Comment by michelboaventura** [comment]
Implementado em https://github.com/byebnk/zoop_ruby/pull/9
